[project]
name = "daydream-watcher"
version = "0.1.2"
description = "Prometheus metrics exporter for Daydream signups"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "prometheus-client>=0.22.1",
    "requests>=2.32.5",
]
