{
 "title": "Daydream signup stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Daydream stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "📜 Total signups",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(daydream_signups)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🏙️ Daydream events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (event_name) (daydream_signups)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cities with the most new signups (past 24h)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(increase(daydream_signups[24h])))",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "🔥 New signups today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(daydream_signups[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signups over time",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sort_desc(daydream_signups != 0)",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  { "title": "Metrics exporter info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Exporter program info",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 29 },
   "targets": [
    { "expr": "python_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"daydream_watcher\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Process CPU time (each second)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"daydream_watcher\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}